version: '3'
services:
  db-postgres:
    image: postgres
    container_name: db-postgres
    environment:
      POSTGRES_DB: socks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5333:5432"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-java
    ports:
      - "8085:8082"
    restart: always
    depends_on:
      - db-postgres
